version: '3'
services:
  server:
    container_name: server
    image: kimjiseop/jaetteoli-server
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: "always"
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: kimjiseop/jaetteoli-nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - "server"

