version: '3'
services:
  server:
    container_name: server
    image: kimjiseop/jaetteoli-server
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: "always"
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: kimjiseop/jaetteoli-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - "server"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./letsencrypt-log:/var/log/letsencrypt
      - ./renew-script.sh:/renew-script.sh
    entrypoint: "/renew-script.sh"