server:
  port: ${SERVER_PORT:8080}
spring:
  main:
    allow-circular-references: true

    mvc:
      path match:
        matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379

  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{secrets.PROD_DB}}
    username: ${{ secrets.RDS_USER_NAME }}
    password: ${{ secrets.RDS_PW }}


  jwt:
    secret: ${{ secrets.JWT_TOKEN }}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
