server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  redis:
    host: redis
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwt:
    secret: ${JWT_TOKEN}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mail:
  smtp:
    port: 587
    socketFactory:
      port: 465
      fallback: true
    auth: true
    starttls:
      enable: true
      required: true

adminMail:
  id: ${ADMIN_MAIL_ID}
  password: ${ADMIN_MAIL_PW}