server:
  port: 5000
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB}
    username: ${RDS_USER_NAME}
    password: ${RDS_PW}
  jwt:
    secret: ${JWT_TOKEN}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
