server:
  port: 5000
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://jaetteoli.cswo92uen0rv.ap-northeast-2.rds.amazonaws.com/jiseop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: tjddls1920$

  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
