server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
  config:
    import:
      - application-aws.yml
  jwt:
    secret: ${JWT_TOKEN}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
